bigquery/README.md, bigquery/docker-compose.yml
I realized #13 broke using running indexer for different datasets for local deployment.
Before #13:
* Elasticsearch started by docker-compose in data-explorer repo
* indexer.py runs against localhost:9200. 
After #13:
* indexer indexes into Elasticsearch container from this repo's `docker-compose.yml`.
After this PR:
* Elasticsearch started by docker-compose in data-explorer repo
* indexer indexes into Elasticsearch container from *data-explorer repo*
=> Use Elasticsearch container from data-explorer repo

bigquery/README.md, bigquery/deploy/README.md
This is safer because there will be fewer Editor/Owners, and it will be easier to verify that all Editor/Owners already have access to BigQuery tables.
=> In deploy instructions, recommend creating a new project

bigquery/indexer.py
The `docker-compose up` command from #22 doesn't actually work. Before this PR:
```
BILLING_PROJECT_ID=google.com:api-project-360728701457 docker-compose up --build
indexer_1        | usage: indexer.py [-h] [--elasticsearch_url ELASTICSEARCH_URL]
indexer_1        |                   [--dataset_config_dir DATASET_CONFIG_DIR]
indexer_1        |                   --billing_project_id BILLING_PROJECT_ID
indexer_1        | indexer.py: error: argument --billing_project_id is required
bigquery_indexer_1 exited with code 2
```
[See here](https://stackoverflow.com/questions/10551117/setting-options-from-environment-variables-when-using-argparse) for an explanation and solution. After this PR, `docker-compose up` works as expected.
=> Fix docker-compose up

bigquery/deploy/README.md, bigquery/indexer.py, indexer_util/indexer_util/indexer_util.py
Instead, add a step to `deploy/README.md` to delete the index.
This way, for datasets like AMP PD that need multiple indexers, the index won't be deleted at the start of every indexer run.
=> Don't delete index in beginning of indexer.py

bigquery/indexer.py
Before this PR, error is:
```
indexer_1        | Traceback (most recent call last):
indexer_1        |   File "indexer.py", line 140, in <module>
indexer_1        |     main()
indexer_1        |   File "indexer.py", line 135, in main
indexer_1        |     args.billing_project_id)
indexer_1        |   File "indexer.py", line 109, in index_facet_field
indexer_1        |     bulk(es, k)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
indexer_1        |     for ok, item in streaming_bulk(client, actions, **kwargs):
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 180, in streaming_bulk
indexer_1        |     client.transport.serializer):
indexer_1        |   File …
```
=> Friendly error message for wrong primary_key

bigquery/indexer.py
I tried indexing Baseline tables with the new `bigquery.json`.
Before this PR: I got this error because the BigQuery tables have some cells that are null:
```
elasticsearch_1    | [2018-07-03T21:58:56,122][WARN ][r.suppressed             ] path: /_bulk, params: {}
elasticsearch_1    | com.fasterxml.jackson.core.JsonParseException: Non-standard token 'NaN': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow
elasticsearch_1    |  at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@5c758f6f; line: 1, column: 1616]
elasticsearch_1    | 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.10.jar:2.8.10]
elasticsearch_1    | 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) …
```
=> Remove nan's before indexing in Elasticsearch

README.md, bigquery/indexer.py
This is needed to workaround an NHS problem where the same column name has 2 types in 2 tables. This will also eventually be needed for exporting selected cohort.
=> Include project/dataset/table name in index

.circleci/config.yml, bigquery/docker-compose.yml, gcs/docker-compose.yml
Prior to docker-compose 1.21.0, running `docker-compose` in data-explorer repo created network dataexplorer_default.
With docker-compose 1.21.0, this changed to data-explorer_default. See "Dashes and underscores in project names are no longer stripped out." in [release notes](https://github.com/docker/compose/releases/tag/1.21.0).
=> Update data-explorer network name

dataset_config/1000_genomes/bigquery.json, indexer_util/indexer_util/indexer_util.py
The use of `scripted_upsert` was incorrect, we just want to use a blank document as the `upsert`.
Makes it so that it doesn't matter if the participants or samples tables are indexed first.
=> Fix upsert for bulk_index_scripts

.circleci/config.yml, bigquery/tests/integration.sh
This seems cleaner to me.
For example, say:
- Make typo in bigquery.json
- Run indexer, index is incorrect
- Fix bigquery.json
- Run test
Before this PR, test would fail. After this PR, test will correctly pass.
Also, run test from bigquery/ instead of project root. With project root, I kept having to change directories, since docker-compose is run from bigquery.
=> Delete index at beginning of integration test instead of end

bigquery/tests/integration.sh, bigquery/tests/integration_golden_index.json, dataset_config/1000_genomes/bigquery.json
Golden file doesn't change; that participant doesn't have fastq.
(Don't forget to create golden files for mapping and fields index when you get a chance.)
=> Add fastq to sample_file_columns

bigquery/tests/1000_genomes_fields_golden.json, bigquery/tests/1000_genomes_golden.json, bigquery/tests/1000_genomes_mappings_golden.json, bigquery/tests/integration.sh, dataset_config/1000_genomes/bigquery.json
Plan is:
- Switch indexer and explorer over to using `human_genome_variants_no_fastq` dataset
- Replace `human_genome_variants` with `human_genome_variants_no_fastq`
- Switch `bigquery.json` configs in indexer and explorer back to `human_genome_variants`
=> Start migration 1000 genomes dataset

bigquery/indexer.py
Encountered some occasional issues where not all of the samples were present in the export samples JSON file. Interestingly this was only happening on linux (not my mac). Sleeping for 5 seconds before scanning through the index seems to resolve the issue––similarly to how we do for the integration test.
=> Wait before creating samples JSON export file

bigquery/README.md, bigquery/deploy/bq-indexer-cronjob.yaml.templ, bigquery/deploy/bq-indexer.yaml.templ, bigquery/docker-compose.yml, bigquery/indexer.py, bigquery/tests/integration.sh, dataset_config/template/deploy.json
From indexer.py:
```
bigquery.Client(project=args.billing_project_id)
```
My next PR will make the indexer work on the new, large NHS table. In it, I will write a temporary table to the deploy dataset. The PR will create another client:
```
bigquery.Client(project=deploy_project_id)
```
So both billing_project_id and deploy_project_id will be charged for billing. To avoid confusion, just use deploy project for all billing and delete BILLING_PROJECT_ID flag.
Why we have BILLING_PROJECT_ID:
First, indexer.py was implemented and run locally. At this time, there was no deploy.json/deploy project. We added BILLING_PROJECT_ID because we didn't have permission to bill the project containing dataset BigQuery tables (eg AMP PD project).
FYI @malathi13
=> Remove BILLING_PROJECT_ID flag

bigquery/README.md, bigquery/docker-compose.yml
Switch elasticsearch back to starting with the default heap size, but add an easy ENV for customizing it when indexing larger datasets with a more powerful computer.
`docker-compose up elasticsearch`: Uses the ES default of 256MB for the java heap, which should work on all computers but may run out of memory when indexing large datasets.
`ES_JAVA_OPTS="-Xms10g -Xmx10g" docker-compose up elasticsearch`: Uses 10GB for the java heap, which may not work on all computers but will perform far better for large datasets.
FYI @malathi13
=> Add env for customizing ES heap size

indexer_util/indexer_util/indexer_util.py
I saw this while periodically while indexing NHS:
```
indexer_1_23dcc3c190fa | Traceback (most recent call last):
indexer_1_23dcc3c190fa |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 149, in perform_request
indexer_1_23dcc3c190fa |     response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
indexer_1_23dcc3c190fa |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
indexer_1_23dcc3c190fa |     _stacktrace=sys.exc_info()[2])
indexer_1_23dcc3c190fa |   File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 333, in increment
indexer_1_23dcc3c190fa |     raise six.reraise(type(error), error, _stacktrace)
indexer_1_23dcc3c190fa |   File …
```
=> Increase request timeout to 300s

bigquery/README.md, bigquery/deploy/README.md
deploy README seems like a better place since it's GKE related.
=> Move local-ui-index-gke instructions to deploy README

bigquery/deploy/README.md
I got this error while indexing Baseline internal, because there's a view.
google.api_core.exceptions.Forbidden: 403 GET https://www.googleapis.com/bigquery/v2/projects/baseline-data-explorer/datasets/dataset_for_view_exports: Access Denied: Dataset baseline-data-explorer:dataset_for_view_exports: The user indexer@baseline-data-explorer.iam.gserviceaccount.com does not have bigquery.datasets.get permission for dataset baseline-data-explorer:dataset_for_view_exports.
=> In README, change indexer role from BigQuery Job User to BigQuery Admin

kubernetes-elasticsearch-cluster/create-cluster.sh
So we get security updates. The [PodDisruptionBudgets](https://github.com/DataBiosphere/data-explorer-indexers/pull/124) should keep Data Explorer working during an upgrade.
I ran the script and confirmed in GKE UI that autoupgrade is now on.
=> Turn on autoupgrade for GKE cluster

bigquery/deploy/README.md, bigquery/deploy/deploy-indexer.sh, kubernetes-elasticsearch-cluster/create-cluster.sh, kubernetes-elasticsearch-cluster/deploy-es.sh
Tested by:
1) Have a data-explorer already deployed with 1000_genomes data.
2) Run the scripts. Make sure the data-explorer does not go down during this time.
3) Once the scripts run, verify data-explorer is running off the new version.
4) Delete the old cluster. Verify data-explorer is still running.
=> Update scripts to reindex with no downtime

bigquery/deploy/README.md, bigquery/deploy/deploy-indexer.sh, kubernetes-elasticsearch-cluster/deploy-es.sh, util/setup-gcloud.sh
So I don't have to manually run the gcloud/kubectl setup commands, for example when [running a local UI with an index from GKE](https://github.com/DataBiosphere/data-explorer-indexers/tree/master/bigquery/deploy#running-a-local-ui-with-an-index-from-gke).
=> Create standalone script setup-gcloud.sh

bigquery/indexer.py, indexer_util/indexer_util/indexer_util.py, kubernetes-elasticsearch-cluster/es-master-stateful.yaml
FYI @lgolowich 
The field limit problem was hard to debug. For some reason GKE container logs weren't showing the detailed error message. They had:
```
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception', u'[es-master-0][10.60.2.5:9300][indices:admin/mapping/put]')
```
When I ran locally, then I saw the error message:
```
'Limit of total fields [1000] in index [baseline_cdr] has been exceeded'
```
Not sure why error message wasn't in StackDriver logs.
=> Changes needed for reindexing Baseline internal

bigquery/indexer.py, bigquery/tests/framingham_heart_study_teaching_dataset_fields_golden.json, bigquery/tests/integration.sh, indexer_util/indexer_util/indexer_util.py, kubernetes-elasticsearch-cluster/es-master-stateful.yaml
Earlier I indexed Baseline with time_series_column=study_day. This turned out to be excessive. There are hundreds if not thousands of fields; each field has ~700 study days. The UI was very slow to load; searches were very slow; after clicking on a bar the update was slow.
I'm not sure we want to support this many subfields.
One advantage of lower timeout is, if things are completely broken, you find out sooner.
Also update Framingham golden file. I changed the first line of the test to `#!/bin/bash -x`. Normally I only add the `-x` for debugging if things are broken, but in this case it's good to always have. Without it, it was [hard to tell what failed](https://circleci.com/gh/DataBiosphere/data-explorer-indexers/887).
=> Undo some of the changes for Baseline
