DataBiosphere/data-explorer-indexers

bigquery/config/platinum_genomes/facet_fields.csv
bigquery/config/template/facet_fields.csv
bigquery/indexer.py
bigquery/requirements-to-freeze.txt
bigquery/requirements.txt

Add column header to facet_fields.csv.

Remove json and csv comments using jsmin.

---

.gitignore
bigquery/README.md
bigquery/config/platinum_genomes/facet_fields.csv

Fixes #7. The reason you saw the error in #7 was because you forgot this step from the README:
```
Change project names in config/platinum_genomes/facet_fields.csv.
```
This PR changes project id in config/platinum_genomes/facet_fields.csv, so if people skip that step, the error will be more obvious.

Change project id in sample facet_fields.csv.

---

.gitignore
bigquery/README.md
bigquery/config/platinum_genomes/dataset.json
bigquery/config/platinum_genomes/facet_fields.csv
bigquery/config/template/dataset.json
bigquery/config/template/facet_fields.csv
bigquery/indexer.py

Add more information about setting up config directory

---

.circleci/config.yml
bigquery/indexer.py

FYI I tried prettier python and ran into https://github.com/prettier/plugin-python/issues/73. so sticking with yapf. :)

 Initial yapf lint + CircleCI config

---

bigquery/deploy/README.md

Instructions for configuring a service account

---

bigquery/deploy/README.md

Old: baseline-data-explorer-indexer@DATASET-data-explorer.iam.gserviceaccount.com
New: indexer@DATASET-data-explorer.iam.gserviceaccount.com

Shorten recommended service account name

---

bigquery/deploy/bq-indexer-cronjob.yaml.templ
bigquery/deploy/bq-indexer.yaml.templ
bigquery/deploy/deploy-indexer.sh

GKE has some neat extras for this, like metrics/visualizations, and features like pause/resume.

Daily recurring cronjob for the bq-indexer

---

.circleci/config.yml
bigquery/indexer.py
gcs/indexer.py
indexer_util/indexer_util/indexer_util.py

@melissachang This isn't quite the format we discussed, though I think it is useful to have the counts to use as a facet in the UI. Can also flatten it to `bam_paths`, bams_count`, etc. if you think that'd be better.

Index GCS files into elasticsearch

---

.circleci/config.yml

Sorry forgot to push before merging...

Circle comment fixes

---

dataset_config/1000_genomes/bigquery.json

Even though they're identical, I figure it's better to use the new one. Eg if they change the new one.

Use new 1000 Genomes sample_info

---

bigquery/deploy/README.md

Minor changes to BigQuery deploy README

---

bigquery/indexer.py

Add a prefix to sample facet fields

---

bigquery/indexer.py

I noticed things didn't work with my test project (`google.com:api-project-360728701457`).

Support . and : in project id

---

bigquery/tests/1000_genomes_fields_golden.json
bigquery/tests/1000_genomes_golden.json
bigquery/tests/1000_genomes_mappings_golden.json
dataset_config/1000_genomes/bigquery.json

Copied the table without fastq back to the original dataset.

Migrate 1000 genomes table name

---

bigquery/README.md

Resolves #73.
Happy to tweak the wording!

Clarify documentation about ID columns in BQ indexer.

---

bigquery/README.md

README tips for indexing large tables

---

bigquery/requirements.txt
indexer_util/requirements.txt

Fixes https://github.com/DataBiosphere/data-explorer/issues/200

Upgrade requests lib

---

bigquery/README.md

Add instructions for having local UI read from ES on GKE

---

kubernetes-elasticsearch-cluster/deploy-es.sh

Before this PR:
- If deploy.json doesn't have node_pool_num_replicas, es-data-stateful-deploy.yaml has "replicas: null" and deployed es-data has 1 replica
After this PR:
- If deploy.json doesn't have node_pool_num_replicas, es-data-stateful-deploy.yaml has "replicas: 3" and deployed es-data has 3 replicas

Fix default number of master and data replicas

---

bigquery/deploy/deploy-indexer.sh
kubernetes-elasticsearch-cluster/create-cluster.sh
kubernetes-elasticsearch-cluster/deploy-es.sh

Sometimes I accidentally will deploy for the wrong dataset or project

Bold some lines in deployment scripts

---

bigquery/indexer.py

Use sample_id_column name from config instead of hard coded 'sample_id'

---

bigquery/deploy/deploy-indexer.sh
kubernetes-elasticsearch-cluster/deploy-es.sh

This was a lot easier to catch once I tried deploying several projects at once.

Minor script fixes - set project before listing clusters

---

bigquery/indexer.py
bigquery/tests/1000_genomes_mappings_golden.json

Using the simple analyzer makes the tokenizer split on any non-alphanumeric character, including underscores.
q=phd
Before:
https://screenshot.googleplex.com/DZCQMNVCm94
After:
https://screenshot.googleplex.com/K0N4abC7Up9
q=female
Before:
https://screenshot.googleplex.com/ANF6NQw36E6
After:
https://screenshot.googleplex.com/7kiQVTQuCma

Use simple analyzer on indexes. 

---

bigquery/deploy/README.md
util/delete-cluster.sh

I used this script this morning when cleaning up all the old clusters.

Script for deleting oldest cluster

---

bigquery/indexer.py
bigquery/tests/1000_genomes_fields_golden.json
bigquery/tests/framingham_heart_study_teaching_dataset_fields_golden.json

Removed participant and sample id columns from fields index

---

kubernetes-elasticsearch-cluster/es-data-pdb.yaml
kubernetes-elasticsearch-cluster/es-master-pdb.yaml

Fixes issues mentioned in (examples) https://github.com/grafana/loki/issues/9365 and https://hunj.dev/no-matches-for-kind-poddisruptionbudget-in-version-policy-v1beta1/

Update apiVersion for PodDisruptionBudget
